* Formal Foundations for Modeling Robot Manipulators

[[https://travis-ci.com/affeldt-aist/coq-robot][file:https://travis-ci.com/affeldt-aist/coq-robot.svg?branch=master]]

** Contents

This library is a formalization of the mathematics of rigid body
transformations in the Coq proof-assistant. It can be used to address
the forward kinematics problem of robot manipulators. It contains
theories for angles, three-dimensional geometry (including
three-dimensional rotations, skew-symmetric matrices, quaternions),
rigid body transformations (isometries, homogeneous representation,
Denavit-Hartenberg convention, screw motions), and an application to
the SCARA robot manipulator.

** License

The license for this library's original contents is LGPL v3
(https://www.gnu.org/copyleft/lesser.html).

** Authors

see [[AUTHORS.md]]

** Files

see [[FILES.md]]

** Installation

- ~git clone git@github.com:affeldt-aist/coq-robot.git~
- ~cd coq-robot~

If opam is installed, do:

1. ~opam install .~

opam takes care of the dependencies.

If opam is not installed but if the Requirements (see below) are met, do:

1. ~make~
2. ~make install~
   
** Requirements

- [[https://coq.inria.fr/][The Coq proof-assistant]] 8.11
- [[https://github.com/math-comp/math-comp][The Mathematical Components library]] 1.11.0
- [[https://github.com/math-comp/real-closed][Theorems for real closed fields]] 1.1.1
  + requires [[https://github.com/math-comp/bigenough][bigenough]] 1.0.0
- [[https://github.com/math-comp/analysis][Analysis library compatible with Mathematical Components]] 0.3.1
  + requires [[https://github.com/math-comp/finmap][finmap]] 1.5.0

** References

Main reference:
- Reynald Affeldt and Cyril Cohen.
  Formal foundations of 3D geometry to model robot manipulators.
  In 6th ACM SIGPLAN Conference on Certified Programs and Proofs (CPP 2017),
  Paris, France, January 16--17, 2017, pages 30--42. ACM Press, Jan 2017
  [[http://staff.aist.go.jp/reynald.affeldt/documents/robot_cpp_long.pdf][pdf]]

Some references used in this work:
- [murray] Murray, Li, Shankar Sastry: A Mathematical Introduction to Robotic Manipulation
- [springer] Siciliano, Khatib (Eds.): Springer Handbook of Robotics
- [angeles] Angeles: Fundamentals of Robotic Mechanical Systems
- [oneill] O'Neill: Elementary Differential Geometry
- [spong] Spong, Hutchinson, Vidyasagar: Robot Modeling and Control
- [sciavicco] Sciavicco, L., Siciliano, B.: Modelling and Control of Robot Manipulators
